### ISSUE TITLE
Add 1.88 build to repo

### ISSUE THREAD

**Issue by LordFlashmeow** [maresb/docker-build-s3fs#6]
v1.88 has been released on github.

Can you add this version to the build list and add the .deb package?

I was looking at revisions_to_build.txt and didn't see a line 1.87 even though there's a package uploaded, so I wasn't sure if the file is updated or not. If the version should go in the file, I can make a PR with the new release.

https://github.com/maresb/docker-build-s3fs/blob/8f7220d96e06e41070f617332a383b563ca4a155/builds/revisions_to_build.txt#L1-L6

**Comment by maresb** [comment]
Thanks for letting me know! I missed the notification from the 1.88 release.

Also thanks for letting me know about `revisions_to_build.txt`. Looks like I forgot about my script for the 1.87 release.

Please let me know if you have any issues since I haven't thoroughly tested. (Seems to at least build and execute under both 18.04 and 20.04.)
